### PR TITLE
Add testsuite

### PR DESCRIPTION
**Pull request by aylen384**
Add testsuite (analog to https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/395)

### CODE REVIEW

**Comment by aylen384** [comment]
@okurz We need travis to be enabled for this repo.

**Comment by okurz** [comment]
@coolo please enable https://travis-ci.org/os-autoinst/os-autoinst-needles-openQA or give admin rights to someone else, I can't enable the repo to build

**Comment by coolo** [comment]
the 'giving admin rights' part failed before - so I just clicked the button

**Comment by okurz** [comment]
Seems I can actually disable/enable builds again on https://travis-ci.org/os-autoinst/os-autoinst-needles-openQA/settings but maybe the initial enabling of the travis project at all is/was not allowed for me

**Pull request merged**
